configfile: "config.yaml"

import os

# make sure the tmp directory exists
#os.makedirs(config['tmp_dir'], exist_ok=True)

rule all:
    input:
        expand("data/bam/{sample}.bam", sample = config['samples']),
        expand("data/bed/{sample}.bed", sample = config['samples']),
        expand("data/bigwig/{sample}.{strand}.bw", sample = config['samples'], strand = ["plus", "minus"])

rule trimmo:
    input: "/Path_to_your_data/{sample}.fastq.gz"
    output: "clean/{sample}.fastq.gz"
    threads: 8
    params:
        min_len = config['minReadLength']
    shell:
        """
        trimmomatic SE -threads {threads} {input} {output} ILLUMINACLIP:/Path_to_your_adaptor_file/adapers/Trimmomatic/TruSeq3-SE.fa:2:30:7 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:{params.min_len}
        """

rule bowtie2:
    input: "clean/{sample}.fastq.gz"
    output: "data/bam/{sample}.bam"
    threads: 8
    log: "logs/{sample}.bowtie2.log"
    params:
        index = config['genomeIndex']
    shell:
        """
        bowtie2 -N 1 -L 25 -p {threads} -x {params.index} -U {input} -S 2> {log} {wildcards.sample}.sam
        samtools sort -@ {threads} -T {wildcards.sample} -o {output} {wildcards.sample}.sam
        rm {wildcards.sample}.sam
        """

rule bam_2_bed:
    input: "data/bam/{sample}.bam"
    output: "data/bed/{sample}.bed"
    shell:
        """
        samtools view -bq 3 {input} | bedtools bamtobed -i - | bedtools intersect -v -a - -b /data_path/hg19.BLACKLISTED.MERGED.bed | grep -v 'hap' | grep -v 'random' | grep -v 'chrUn' | grep -v 'chrM' > {output}
        """

rule bed_2_bedgraph:
    input: "data/bed/{sample}.bed"
    output:
        plus = "data/bedGraph/{sample}.plus.bedgraph",
        minus = "data/bedGraph/{sample}.minus.bedgraph"
    shell:
        """
        rpm=$(wc -l {input} | cut -f 1 -d ' ' | awk '{{printf "%f\\n", $1/1000000.0}}')
        rpm=$(echo "1 / $rpm" | bc -l)
        bedtools genomecov -bg -scale $rpm -strand + -i {input} -g /data_path/hg19.chrom.sizes.txt | bedtools sort -i - > {output.plus}
        bedtools genomecov -bg -scale $rpm -strand - -i {input} -g /data_path/hg19.chrom.sizes.txt | bedtools sort -i - > {output.minus}
        """

rule bedgraph_2_bw:
    input: "data/bedGraph/{sample}.{strand}.bedgraph"
    output: "data/bigwig/{sample}.{strand}.bw"
    shell:
        """
        bedGraphToBigWig {input} /data_path/hg19.chrom.sizes.txt {output}
        """



